import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import { Button, ButtonGroup, Divider } from "@nextui-org/react";
import { Providers } from "./root_layout";
import { IoIosStar } from "react-icons/io";

const inter = Inter({ subsets: ["latin"] });
const bebas = Bebas_Neue({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "1000 Películas",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
    apple: "/icon512_maskable.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="fixed h-full overflow-hidden">
      <body className="overscroll-none w-[100vw] ">
        <Providers>
          <main className="min-h-screen flex justify-between flex-col dark text-xl  ">
            <div className="flex items-center flex-col w-full justify-center p-8  gap-2">
              <div className="flex items-center justify-center  gap-5">
                <IoIosStar size={40} className="pb-1 " />
                <h1 className={`${bebas.className} text-6xl `}>CARTELERA</h1>
                <IoIosStar size={40} className="pb-1" />
              </div>
              <Divider className=" h-1 w-[90%]" />
            </div>
            {children}
            <div className="flex items-center w-full justify-center p-10">
              <ButtonGroup className="text-xl">
                <Button className={`${bebas.className} text-2xl `}>
                  Random
                </Button>
                <Button className={`${bebas.className} text-2xl `}>
                  Lista
                </Button>
                <Button className={`${bebas.className} text-2xl `}>
                  Vistas
                </Button>
              </ButtonGroup>
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
